name: rsgislib-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - gdal
  - geos
  - gsl
  - kealib
  - xerces-c
  - muparser
  - boost-cpp
  - rsgislib
  - rios
  - scikit-learn
  - scikit-image
  - scikit-optimize
  - imbalanced-learn
  - scikit-plot
  - scikit-fuzzy
  - bayesian-optimization
  - matplotlib
  - pandas
  - geopandas
  - statsmodels
  - h5py
  - scipy
  - rasterio
  - shapely
  - networkx
  - sqlalchemy
  - pycurl
  - xgboost
  - lightgbm
  - seaborn
  - plotly
  - python-kaleido
  - fiona
  - elevation
  - rtree
  - tqdm
  - pygal
  - pysal
  - libpysal
  - esda
  - pyyaml
  - netcdf4
  - xarray
  - psutil
  - bokeh
  - pytables
  - pip
  - pip:
    - pyod
    - cvxopt
    - gsutil
    - feather-format
    - openpyxl
    - SALib
    - alphashape
    - xlsxwriter
    - pysptools
    - pymcr
